### ISSUE TITLE
This driver is amazing...! But is there a way to control it remotely?

### ISSUE THREAD

**Issue by filmgarage** [linusg/rpi-backlight#42]
Thank you so much for this great piece of work!

It runs great on a small touch screen that I built as a clock for my mother who is getting old and keeps forgetting what day it is... I run AppDaemon with Home Assistant on the device. Unfortunately, Home Assistant and AppDaemon are running in dock images and cannot control the host system and hence have no control over the display. Home Assistant would have beentje perfect companion to dim the screen in the evenings... Is there a way to send the commands to the screen remotely? It is not possible to connect with ssh from docker image to host system. MQTT would be fine, for example...

![IMG_3819](https://user-images.githubusercontent.com/30559371/141205700-5e36f3e6-bcd3-4172-9d2a-e21851fbf60d.jpeg)

**Comment by linusg** [comment]
> Unfortunately, Home Assistant and AppDaemon are running in dock images and cannot control the host system and hence have no control over the display. Home Assistant would have beentje perfect companion to dim the screen in the evenings...

This might be possible if you can mount the relevant files of the sysfs into the container as a rw volume.

> It is not possible to connect with ssh from docker image to host system. MQTT would be fine, for example...

MQTT from where - within the container? If you can manage to get that working, then surely SSH would work as well. But yeah, you can of course write a simple MQTT or HTTP receiving script that runs on the host and controls the screen that way.

**Comment by filmgarage** [comment]
Thanks for your immediate response!!! My knowledge of filesystems etc is very limited, I get around but have no idea about the internal workings... Light and sensors are my cup of tea so that would be easier for me to grasp. But could you put me on the right track how I could mount these relevant files into the docker container?

**Comment by filmgarage** [comment]
Googling "sysfs" was enough to get me started. But I guess I would only be able to access a file, not run your command line controls... Would it be an possible to write to a file on the host system using"syses" with the values of the screen intensity and dimming speed and have a routine scanning the file for changes on the host that would change the dimming accordingly?

**Comment by linusg** [comment]
> Would it be an possible to write to a file on the host system using"syses" with the values of the screen intensity and dimming speed and have a routine scanning the file for changes on the host that would change the dimming accordingly?

The whole idea of mounting files from the host into the container is that any changes are reflected immediately; it's the same file. You can write from the container and read from the host, or vice versa. See here: https://docs.docker.com/storage/bind-mounts/
In theory mapping the right sysfs files and installing the CLI or a custom Python script into the container could be enough for the host kernel to recognize a value change and invoke the display driver.

**Comment by filmgarage** [comment]
Cool! Thanks!!! I hope I will be able to figure out the bind-mounts. Looks like I would be able to master that... But I will have to search for someone to write me a Python script... Are you interested? ;-)

**Comment by filmgarage** [comment]
More people have been looking for a solution:
https://www.reddit.com/r/homeassistant/comments/9qjnf4/control_raspberry_pi_display/
A user comments on using "fabric"
Does that make sense?

**Comment by linusg** [comment]
if you get that bind-mount working, it should just be a matter of creating a custom python script in home-assistant (see https://www.home-assistant.io/integrations/python_script/) and having it run at a certain time of the day (like a cron job; I'm certain they got a scheduler of sorts). Probably a two-liner, literally:

```python
from rpi_backlight import Backlight
backlight = Backlight()
backlight.brightness = 20  # or whatever
# optionally `backlight.power = False` instead
```

> A user comments on using "fabric"
> Does that make sense?

apparently not :)

> Thanks. I will try this if fabric fails.
>
> edit Fabric failed. Use the above.

**Comment by filmgarage** [comment]
Home Assistant is all about scheduling, it's like "cron on testosteron", There are also great integrations that can help like 'adaptive lighting' and 'circadian lighting'. Easy to fine-tune using these helpers.

- But if I understand you correctly: the backlight brightness is already registered in a specific file on the host?
- Which file is this?
- And if I run this script on the docker image I guess I would have to install the rip_backlight driver there as well?
- Would it also be possible to set the dimming speed?
- Last question: how does this python script know how and where to write the value? Or is that part of the rpi_backlight library?

**Comment by filmgarage** [comment]
PS: I read the following about python scripts on Home Assistant:
"It is not possible to use Python imports with this integration. If you want to do more advanced scripts, you can take a look at AppDaemon or pyscript"
I do however have AppDaemon running on my machine as well...

**Comment by linusg** [comment]
> But if I understand you correctly: the backlight brightness is already registered in a specific file on the host?

Right, and reading and writing to those files is basically everything this project does :)

> Which file is this?

https://github.com/linusg/rpi-backlight/blob/33b613ebfbc25becadca07e46314da9b4865f444/rpi_backlight/__init__.py#L29

\+

https://github.com/linusg/rpi-backlight/blob/33b613ebfbc25becadca07e46314da9b4865f444/rpi_backlight/__init__.py#L207

-> `/sys/class/backlight/rpi_backlight/brightness`

> And if I run this script on the docker image I guess I would have to install the rpi_backlight driver there as well?

Yes; I don't know how you use docker, but docker-compose can do this during container startup for you.

> Would it also be possible to set the dimming speed?

Sure, please read the [docs](https://rpi-backlight.readthedocs.io/en/latest/usage.html#python-api).

> Last question: how does this python script know how and where to write the value? Or is that part of the rpi_backlight library?

Yes, it is.

**Comment by filmgarage** [comment]
Great, I am going to try and figure it out, now I need some sleep first...

;-)

Thanks a lot for explaining all this!!!

**Comment by filmgarage** [comment]
Not an easy road but I think I managed to get it working:
- bind-mount was quite a challenge and it turns out I would have to fix that after every update of home-assistant because the update would delete the custom mapping.
- But it turns out that a couple of locations are already mounted on the host. `/config` is bound to `/usr/share/hassio/homeassistant` on the host.
- Therefore I created two symbolic links from the folder `/usr/share/hassio/homeassistant/rpi_brightness`: one to brightness and one to bl_power in: `/sys/class/backlight/rpi_backlight`

Now I can change the value of these two files through the symlinks and the screen will be set to a brightness (0-100%) e.g. `echo 33 > brightness` and can be switched off: ` echo 1 > bl_power` or switched on: `echo 0 > bl_power`

Home Assistant needs to run these shell commands:
In configuration.yaml add:
```
shell_command:
  rpi_screen_off: 'echo 1 > /config/rpi_brightness/bl_power'
  rpi_screen_on: 'echo 0 > /config/rpi_brightness/bl_power'
  # for the brightness it gets a little bit more complicated, it needs to run the bash shell as well as the command
  # shell_command itself cannot handle the template:
  rpi_screen_set_template: >
    bash -c 'echo {{ states("input_number.rpi_brightness") | round(0) }} > /config/rpi_brightness/brightness'

  ## don't forget to add the helper: input_number.rpi_brightness !!! (value 0 - 100)
  ## it may be advisable to have a value between 10 and 100. All values below 10 are not really usable
```

Now I only need an automation that runs the command when the value of `input_number.rpi_brightness` changes:

```
automation:
  - id: '1636653194360'
    alias: Screen Rpi
    description: ''
    trigger:
    - platform: state
      entity_id: input_number.rpi_brightness
    condition: []
    action:
    - service: shell_command.rpi_screen_set_template
    mode: single
```
That's all folks! Thanks for helping me out!
